config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "tasks#home"
  get "tasks", to: "tasks#index"
  post "tasks", to: "tasks#create"
  get "tasks/new", to: "tasks#new", as:"new_task"
  get "tasks/:id/edit", to: "tasks#edit", as:"edit_task"
  patch "tasks/:id", to: "tasks#update"
  get "tasks/:id", to: "tasks#show", as: "details"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def home
  end

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    @completed = @task.completed
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1> Edit your Task</h1>

<%= simple_form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.input :title %>
  <%= f.label :details %>
  <%= f.input :details %>
  <%= f.label :completed %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/home.html.erb
<h1>Home Page <h1>

<%= link_to "Mes Tasks", tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<%@tasks.each do |task|%>
  <input type="checkbox" <%if task.completed == true %>
  <%= "checked".html_safe %>
  <% end %>>
  <%= link_to task.title, details_path(task) %> <br> <br>
<%end%>

<%= link_to "New Task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<%= link_to "Edit Task", edit_task_path %>

<div>
  <p><%= @task.details %> </p>
</div>
<div>
  <input type="checkbox" <%= @completed ? "checked".html_safe : "" %>>
  <p><%= @completed ? "this task is completed" : "this task is not yet completed" %></p>
</div>

<%= link_to "Back to list" , tasks_path %>